fix: Use correct rules for `ephemeralcontainers`
kubewarden/allowed-proc-mount-types-psp-policy pull request #58
Opened 2024-07-17 12:34 UTC by viccuad

## Description

Relates to https://github.com/kubewarden/allowed-proc-mount-types-psp-policy/issues/57

Set correct rules for `ephemeralcontainers`.
Prepare for release.

## Test

CI

## Additional Information

### Tradeoff

### Potential improvement

2024-07-17 14:07 UTC, jvanz approved these changes

2024-07-17 14:09 UTC, flavio requested changes

2024-07-17 14:26 UTC, viccuad commented on artifacthub-pkg.yml
> +      - ephemeralcontainers
Well spotted. I have amended the PR to drop `ephemeralcontainers`, will keep https://github.com/kubewarden/allowed-proc-mount-types-psp-policy/issues/57 open to work on audit-scanner.

2024-07-17 14:36 UTC, flavio commented on artifacthub-pkg.yml
> +      - ephemeralcontainers
Yeah, I think for audit-scanner we have to handle the case of a policy that is targeting **only** a sub-resource. I don't think this is something common, we could just track it and work on that when someone complains about that

2024-07-18 07:49 UTC, flavio approved these changes

2024-07-18 08:32 UTC, viccuad commented on artifacthub-pkg.yml
> +      - ephemeralcontainers
In my opinion the audit-scanner should we working seamlessly already; I don't think it sees a difference between a resource or a subresource. Hence why the policy was already being triggered by the audit-scanner.

Nevertheless, I opened https://github.com/kubewarden/audit-scanner/issues/322 for bookeeping.

2024-07-18 08:32 UTC, merged

2024-07-18 08:33 UTC, viccuad commented
tagged in main as 0.1.10.